### ISSUE TITLE
This error message appears after installing the plugin [Main content Goes here]

### ISSUE THREAD

**Issue by tocri** [eduramiba/moodle-theme-uikit#11]
Hello, I use a piwik Server, and I installed the analytics plugin (https://moodle.org/plugins/view.php?plugin=local_analytics) and I get this error message

![main content goes here](https://cloud.githubusercontent.com/assets/10110260/5333695/50374a2c-7e7f-11e4-8338-343fc737e5cb.JPG)

If I uninstall the plugin, the error message no longer appears.

Do you have an idea ?

Thanks

**Comment by tocri** [comment]
Yes, only with this theme

**Comment by eduramiba** [comment]
Fixed for next release.
Coincidentally, both plugins were using the same name for analytics function.
