### ISSUE TITLE
Mobile display issue with UIKIT Theme

### ISSUE THREAD

**Issue by nsheehan** [eduramiba/moodle-theme-uikit#12]
Good morning. 

Noticed a display issue on portable devices at https://mediclearn.rppeo.ca
On computers and laptops the menu/blocks are displayed to the Left and content to the Right. If I reduce the screen size or emulate a tablet in the browser, content is resized and displayed okay. When I open the page on a tablet (any browser) the main content is displayed below the menu/blocks, on a computer/laptop the content stays above the menu/blocks when the viewport size is appropriate.

Because I haven't found a way to view the source on the tablet I was wondering if you may know why this is happening. I also noticed that the size of the sidebar remains a percentage of the whole width, should the grid not be 1-1 at lower resolutions? When I take a look I see:
.mdl-width-xlarge-1-5, .mdl-width-xlarge-2-10 {
width: 25%;
}

Thank you in advance. 

Niall

**Comment by eduramiba** [comment]
The fix for this problem will be available on next release
