### ISSUE TITLE
Fixed background

### ISSUE THREAD

**Issue by nsheehan** [eduramiba/moodle-theme-uikit#13]
Good morning, I have been looking for the best option to make the wallpaper selected in the UIKIT Theme General Settings page to set the wall paper to fixed, rather than tiled. With a tiled background scrolling down the page looks wrong. Would like to make this change without modifying core files.

Thank you.
NIall

**Comment by eduramiba** [comment]
Hi,
It's better in this case that you add custom CSS with the styles manager.

The feature is for a tiled background image, and if we add non tiled background we would also need many options to control how the image is positioned.
