### ISSUE TITLE
Support for Moodle 8.1

### ISSUE THREAD

**Issue by yacolinux** [eduramiba/moodle-theme-uikit#14]
Have you planned to support the new Moodle version (8.1.x)?

**Comment by eduramiba** [comment]
Hi,
Apart from the styles problem in califications (Issue #15), what other new problems have you encountered in Moodle 8.1?

**Comment by yacolinux** [comment]
Que tal Eduardo, acabo de hacer un nuevo posteo corrigiendo el anterior.
Desde ya quería darte las gracias por tu tiempo.

El problema que tuve, lo resolví. Bajé el nuevo código y reemplacé por
completo el código anterior de Uikit, luego de actualizar la DB de Moodle,
todo funcionó perfectamente.

Gracias de vuelta.

Dardo

2015-02-15 14:48 GMT-03:00 Eduardo Ramos <notifications@github.com>:

**Comment by eduramiba** [comment]
Hola Dardo,
Gracias por probar los últimos cambios, creo que pronto haré release de una nueva versión.
