### ISSUE TITLE
Two students name columns showed in Califications

### ISSUE THREAD

**Issue by yacolinux** [eduramiba/moodle-theme-uikit#15]
Using the latest Moodle 8.1+, when you select the "Califications" option, two columns showing the names of the studens appear, the expected one in the main block, and a floating column, attached to the left border of the screen. The menu items below the floating column are not clickeable, but the names of the students are.

**Comment by yacolinux** [comment]
I'm going to correct myself on this one. I've just downloaded again the master.zip, implemented on Moodle, and the grader is working fine right now. Thanks again.

**Comment by eduramiba** [comment]
Hi, thanks for the feedback.
It was probably due to moodle cache, and when you downloaded the latest code moodle detected that it's a new version and purged caches.
