### ISSUE TITLE
Weird blocks issue

### ISSUE THREAD

**Issue by jderfner** [eduramiba/moodle-theme-uikit#16]
I LOVE this theme. I'm having weird, weird issue, though: when I set blocks to appear on the right-hand side, what I get is a blank space on the right and then the blocks squished into a super-narrow space on the left at the bottom, after all the rest of the page content. So the top of the page looks like this:

![screenshot 2015-01-02 17 15 51](https://cloud.githubusercontent.com/assets/2125526/5601929/836af606-92f6-11e4-9e93-d397bec9d788.png)

And then the bottom looks like this:

![screenshot 2015-01-02 17 14 22](https://cloud.githubusercontent.com/assets/2125526/5601926/8367fc26-92f6-11e4-91b0-997bbc7e8dcc.png)

I fiddled with the layout widths in the visual style manager, but no dice (and it was like this before I started fiddling, with just the defaults).

Any ideas about what I can do to fix this? I'm using Moodle 2.6.

**Comment by eduramiba** [comment]
Hi,
I can't reproduce this.

Did you include some custom css in the style manager that could cause this?
