### ISSUE TITLE
Upgrade FontAwesome 4.3.0

### ISSUE THREAD

**Issue by mruasar** [eduramiba/moodle-theme-uikit#17]
Hi, can you please update FontAwesome to latest version i.e. 4.3 as I maintain fontawesome icon filter therefore it can only work if the core theme is updated to latest version of FontAwesome, and as your theme is using FontAwesome, so those using your theme can benefit with filter as well.

**Comment by eduramiba** [comment]
Hi,
Thanks for the feedback.
I need to update several components to their latest version.

I moved this issue into #18

**Comment by eduramiba** [comment]
Done in #18 for next release
