### ISSUE TITLE
Courses block shifts below Navigation block on iPad Mini Retina

### ISSUE THREAD

**Issue by bollycanuk** [eduramiba/moodle-theme-uikit#20]
Similar to issue 12, the @media query doesn't fix the layout on the front page or in Courses sections. The course content is always pushed to the bottom of the page instead of s=displaying between the left block and right block.

see http://astenjohnson.university

**Comment by eduramiba** [comment]
Hi,
I am not sure what you mean.
Can you attach a sample screenshot?

**Comment by bollycanuk** [comment]
Ok. See the attached image.
![uikit_problem](https://cloud.githubusercontent.com/assets/9040146/6204136/c907573e-b50d-11e4-9dd4-e76855aa8ad7.PNG)

**Comment by bollycanuk** [comment]
Also it looks OK on my iPhone 6 but not on an iPad Retina

**Comment by eduramiba** [comment]
Oh yes, this is the same exact problem as Issue #12 that should be fixed for next release.
Meanwhile you can test it by downloading the code from github.
