### ISSUE TITLE
Support Moodle 2.9 and 3.0

### ISSUE THREAD

**Issue by ouraios** [eduramiba/moodle-theme-uikit#29]
Support Moodle 2.9

**Comment by eduramiba** [comment]
I found that the customizer page javascript needs to be changed due to the inclusion of requirejs in Moodle 2.9.

Did you find any other problem?

**Comment by ouraios** [comment]
Actually i don't find any other problem except for the customizer.

**Comment by imgforge** [comment]
Hi guys!  Are you planning on fixing the Customizer issue for 2.9?

**Comment by eduramiba** [comment]
Hi,
A 2.9 release is planned, but I don't have a date yet.

**Comment by imgforge** [comment]
Excellent!  Looking forward to it!  Good work!

**Comment by mauritslamers** [comment]
What exactly needs to be done to get the customizer to work under Moodle 2.9?

**Comment by eduramiba** [comment]
It's a bit tricky because I am including some libraries that use requirejs without using requirejs.
Since Moodle 2.9 now includes requirejs, I must use it to include them. But I also want it to work in versions previous to 2.9, where requirejs is not available.

**Comment by mauritslamers** [comment]
Isn't it possible to have two versions simultaneously? Or to create a separate entry in the Moodle plugin registry which does 2.9 onward?

**Comment by eduramiba** [comment]
Yeah it's possible, I will probably do that.

**Comment by mauritslamers** [comment]
Not sure whether I should create a new issue for this, but in Moodle 2.9 there is a new item in the user menu, called preferences, which doesn't appear in the Dashboard pulldown.

**Comment by nsheehan** [comment]
3.0 Would be nice too. It works but unable to adjust the CSS.

**Comment by eduramiba** [comment]
Once the problem is fixed it should work on 3.0 too.

**Comment by nsheehan** [comment]
Any news on the 2.9+ version of this theme? Anxiously waiting to update.
Cheers.
