### ISSUE TITLE
Save Visual Sthyle manager

### ISSUE THREAD

**Issue by ouraios** [eduramiba/moodle-theme-uikit#32]
Apparently, when i save once my new settings of Visual Style Manager, it doesn't apply on the site i need to come back in and save a second time to apply the new settings.

**Comment by eduramiba** [comment]
Hi,
May this may be the browser cache? If your styles are there when you come back, then they have successfully saved the first time.

**Comment by ouraios** [comment]
Well i see i need to use the refresh function before save & apply my new styles.
It works fine this way.

Thanks
