### ISSUE TITLE
Upgrade to FontAwesome 4.4

### ISSUE THREAD

**Issue by mruasar** [eduramiba/moodle-theme-uikit#35]
Not an issue, but FontAwesome 4.4 just released with 66 new icons.

**Comment by eduramiba** [comment]
Now included with UIkit 2.23.0 ee419fc

**Comment by eduramiba** [comment]
Updated to 4.5 in commit https://github.com/eduramiba/moodle-theme-uikit/commit/0ced879f1634e5d43e911bb348f606b66f954b19
