### ISSUE TITLE
Slideshow- Non Responsive/Shows on Mobile

### ISSUE THREAD

**Issue by Ktierney** [eduramiba/moodle-theme-uikit#37]
The frontpage slideshow is proving to be less than responsive from Desktop to Tablet, and the "Never Show" option for Mobile is not working. I have it chosen but the slideshow is still showing on mobile devices but as it is not very responsive only a piece of each image.

![img_2234](https://cloud.githubusercontent.com/assets/10246538/9342654/ea4adc9c-45b1-11e5-8a72-7311553e2802.PNG)

**Comment by eduramiba** [comment]
Hi Kristin,
This must be a bug introduced when I changed the slideshow component in a recent release.
It will be fixed for next version.

Thanks for the report.
