### ISSUE TITLE
File picker is broken

### ISSUE THREAD

**Issue by mouneyrac** [eduramiba/moodle-theme-uikit#4]
Hello Eduardo,
thanks for this awesome theme, I find it very easy to modify, the off canvas menu is great, I found many options to match my needs. It's an excellent theme :)

However the filepicker is "broken" on mobile (for example go to private files and try to add a file from the filepicker). Some repositories are displayed on the right of the rep list and some are displayed at the bottom. In both case these div are not displayed on the full width like in clean.

Cheers,
Jerome

**Comment by eduramiba** [comment]
Thanks for the fix, I added it for the next release
