### ISSUE TITLE
Media not charging

### ISSUE THREAD

**Issue by Mautefort** [eduramiba/moodle-theme-uikit#47]
Hello,

I'm using your question type Set Spliting since last year and I really like it. 
My problem today is that neither the audio or the pictures are charging in the "item to be soarted" area. I don't know if it's because it's not upgraded (I'm using Moodle 2.9.8) but I remembered I was able to do this in a previous Moodle version that I owned. I really need to insert audio and it's not workind anymore.

Any suggestions ?

Thank you !

**Comment by eduramiba** [comment]
Hi,
This is the repository for plugin theme-uikit, not a question type https://moodle.org/plugins/theme_uikit
